FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

COPY requirements.txt .

# Add this line to upgrade pip first!
RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt
COPY . .

EXPOSE 8000


CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]